### PR TITLE
MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.16

### PR DESCRIPTION
**Pull request by dpryan79**
R 3.5.1

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge-admin, please rerender

**Comment by dpryan79** [comment]
@bgruening When you have a chance, please merge.

**Comment by bgruening** [comment]
uh, that was fast. Thanks.

**Comment by dpryan79** [comment]
No line no wait for CI testing tonight it seems :)

**Pull request merged**
